// Code generated by scratch generator for coverage of mocks package. DO NOT hand-edit structure lightly.
package mocks_test

import (
	"context"
	"testing"
	"time"

	"github.com/tsdlamongan/whcms/backend/internal/domain"
	"github.com/tsdlamongan/whcms/backend/internal/ports"
	"github.com/tsdlamongan/whcms/backend/internal/ports/mocks"

	"github.com/stretchr/testify/assert"
)

func TestGenerated_MockUserRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockUserRepo{
		CreateFn:  func(ctx context.Context, u *domain.User) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.User, r1 error) { calls["GetByID"] = true; return },
		GetByEmailFn: func(ctx context.Context, email string) (r0 *domain.User, r1 error) {
			calls["GetByEmail"] = true
			return
		},
		UpdateFn: func(ctx context.Context, u *domain.User) (r0 error) { calls["Update"] = true; return },
		UpdatePasswordFn: func(ctx context.Context, id int64, passwordHash string) (r0 error) {
			calls["UpdatePassword"] = true
			return
		},
		SetEmailVerifiedFn: func(ctx context.Context, id int64, at time.Time) (r0 error) { calls["SetEmailVerified"] = true; return },
		SetLastLoginFn:     func(ctx context.Context, id int64, at time.Time) (r0 error) { calls["SetLastLogin"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.User, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		DeleteFn:         func(ctx context.Context, id int64) (r0 error) { calls["Delete"] = true; return },
		ExistsAnyAdminFn: func(ctx context.Context) (r0 bool, r1 error) { calls["ExistsAnyAdmin"] = true; return },
	}

	{
		var ctx context.Context
		var u *domain.User
		m.Create(ctx, u)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var email string
		m.GetByEmail(ctx, email)
	}
	{
		var ctx context.Context
		var u *domain.User
		m.Update(ctx, u)
	}
	{
		var ctx context.Context
		var id int64
		var passwordHash string
		m.UpdatePassword(ctx, id, passwordHash)
	}
	{
		var ctx context.Context
		var id int64
		var at time.Time
		m.SetEmailVerified(ctx, id, at)
	}
	{
		var ctx context.Context
		var id int64
		var at time.Time
		m.SetLastLogin(ctx, id, at)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		m.Delete(ctx, id)
	}
	{
		var ctx context.Context
		m.ExistsAnyAdmin(ctx)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["GetByEmail"], "GetByEmail")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["UpdatePassword"], "UpdatePassword")
	assert.True(t, calls["SetEmailVerified"], "SetEmailVerified")
	assert.True(t, calls["SetLastLogin"], "SetLastLogin")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["Delete"], "Delete")
	assert.True(t, calls["ExistsAnyAdmin"], "ExistsAnyAdmin")

	var z mocks.MockUserRepo
	{
		var ctx context.Context
		var u *domain.User
		z.Create(ctx, u)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var email string
		z.GetByEmail(ctx, email)
	}
	{
		var ctx context.Context
		var u *domain.User
		z.Update(ctx, u)
	}
	{
		var ctx context.Context
		var id int64
		var passwordHash string
		z.UpdatePassword(ctx, id, passwordHash)
	}
	{
		var ctx context.Context
		var id int64
		var at time.Time
		z.SetEmailVerified(ctx, id, at)
	}
	{
		var ctx context.Context
		var id int64
		var at time.Time
		z.SetLastLogin(ctx, id, at)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		z.Delete(ctx, id)
	}
	{
		var ctx context.Context
		z.ExistsAnyAdmin(ctx)
	}
}

func TestGenerated_MockClientRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockClientRepo{
		CreateFn:  func(ctx context.Context, c *domain.Client) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Client, r1 error) { calls["GetByID"] = true; return },
		GetByUserIDFn: func(ctx context.Context, userID int64) (r0 *domain.Client, r1 error) {
			calls["GetByUserID"] = true
			return
		},
		UpdateFn: func(ctx context.Context, c *domain.Client) (r0 error) { calls["Update"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Client, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		SoftDeleteFn: func(ctx context.Context, id int64) (r0 error) { calls["SoftDelete"] = true; return },
		AdjustCreditFn: func(ctx context.Context, clientID int64, delta int64, reason string, relatedInvoiceID *int64) (r0 int64, r1 error) {
			calls["AdjustCredit"] = true
			return
		},
	}

	{
		var ctx context.Context
		var c *domain.Client
		m.Create(ctx, c)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var userID int64
		m.GetByUserID(ctx, userID)
	}
	{
		var ctx context.Context
		var c *domain.Client
		m.Update(ctx, c)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		m.SoftDelete(ctx, id)
	}
	{
		var ctx context.Context
		var clientID int64
		var delta int64
		var reason string
		var relatedInvoiceID *int64
		m.AdjustCredit(ctx, clientID, delta, reason, relatedInvoiceID)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["GetByUserID"], "GetByUserID")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["SoftDelete"], "SoftDelete")
	assert.True(t, calls["AdjustCredit"], "AdjustCredit")

	var z mocks.MockClientRepo
	{
		var ctx context.Context
		var c *domain.Client
		z.Create(ctx, c)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var userID int64
		z.GetByUserID(ctx, userID)
	}
	{
		var ctx context.Context
		var c *domain.Client
		z.Update(ctx, c)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		z.SoftDelete(ctx, id)
	}
	{
		var ctx context.Context
		var clientID int64
		var delta int64
		var reason string
		var relatedInvoiceID *int64
		z.AdjustCredit(ctx, clientID, delta, reason, relatedInvoiceID)
	}
}

func TestGenerated_MockProductRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockProductRepo{
		CreateFn:  func(ctx context.Context, pr *domain.Product) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Product, r1 error) { calls["GetByID"] = true; return },
		GetBySlugFn: func(ctx context.Context, slug string) (r0 *domain.Product, r1 error) {
			calls["GetBySlug"] = true
			return
		},
		UpdateFn: func(ctx context.Context, pr *domain.Product) (r0 error) { calls["Update"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Product, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		SoftDeleteFn:  func(ctx context.Context, id int64) (r0 error) { calls["SoftDelete"] = true; return },
		CreateGroupFn: func(ctx context.Context, g *domain.ProductGroup) (r0 error) { calls["CreateGroup"] = true; return },
		GetGroupByIDFn: func(ctx context.Context, id int64) (r0 *domain.ProductGroup, r1 error) {
			calls["GetGroupByID"] = true
			return
		},
		UpdateGroupFn: func(ctx context.Context, g *domain.ProductGroup) (r0 error) { calls["UpdateGroup"] = true; return },
		ListGroupsFn: func(ctx context.Context, includeHidden bool) (r0 []domain.ProductGroup, r1 error) {
			calls["ListGroups"] = true
			return
		},
		SoftDeleteGroupFn: func(ctx context.Context, id int64) (r0 error) { calls["SoftDeleteGroup"] = true; return },
		UpsertPricingFn:   func(ctx context.Context, pp *domain.ProductPricing) (r0 error) { calls["UpsertPricing"] = true; return },
		GetPricingFn: func(ctx context.Context, productID int64, cycle domain.BillingCycle) (r0 *domain.ProductPricing, r1 error) {
			calls["GetPricing"] = true
			return
		},
		ListPricingFn: func(ctx context.Context, productID int64) (r0 []domain.ProductPricing, r1 error) {
			calls["ListPricing"] = true
			return
		},
		DeletePricingFn: func(ctx context.Context, productID int64, cycle domain.BillingCycle) (r0 error) {
			calls["DeletePricing"] = true
			return
		},
		ListOptionGroupsFn: func(ctx context.Context) (r0 []domain.ConfigurableOptionGroup, r1 error) {
			calls["ListOptionGroups"] = true
			return
		},
		ListOptionsFn: func(ctx context.Context, groupID int64) (r0 []domain.ConfigurableOption, r1 error) {
			calls["ListOptions"] = true
			return
		},
		ListOptionValuesFn: func(ctx context.Context, optionID int64) (r0 []domain.ConfigurableOptionValue, r1 error) {
			calls["ListOptionValues"] = true
			return
		},
		DecrementStockFn: func(ctx context.Context, productID int64) (r0 error) { calls["DecrementStock"] = true; return },
	}

	{
		var ctx context.Context
		var pr *domain.Product
		m.Create(ctx, pr)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var slug string
		m.GetBySlug(ctx, slug)
	}
	{
		var ctx context.Context
		var pr *domain.Product
		m.Update(ctx, pr)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		m.SoftDelete(ctx, id)
	}
	{
		var ctx context.Context
		var g *domain.ProductGroup
		m.CreateGroup(ctx, g)
	}
	{
		var ctx context.Context
		var id int64
		m.GetGroupByID(ctx, id)
	}
	{
		var ctx context.Context
		var g *domain.ProductGroup
		m.UpdateGroup(ctx, g)
	}
	{
		var ctx context.Context
		var includeHidden bool
		m.ListGroups(ctx, includeHidden)
	}
	{
		var ctx context.Context
		var id int64
		m.SoftDeleteGroup(ctx, id)
	}
	{
		var ctx context.Context
		var pp *domain.ProductPricing
		m.UpsertPricing(ctx, pp)
	}
	{
		var ctx context.Context
		var productID int64
		var cycle domain.BillingCycle
		m.GetPricing(ctx, productID, cycle)
	}
	{
		var ctx context.Context
		var productID int64
		m.ListPricing(ctx, productID)
	}
	{
		var ctx context.Context
		var productID int64
		var cycle domain.BillingCycle
		m.DeletePricing(ctx, productID, cycle)
	}
	{
		var ctx context.Context
		m.ListOptionGroups(ctx)
	}
	{
		var ctx context.Context
		var groupID int64
		m.ListOptions(ctx, groupID)
	}
	{
		var ctx context.Context
		var optionID int64
		m.ListOptionValues(ctx, optionID)
	}
	{
		var ctx context.Context
		var productID int64
		m.DecrementStock(ctx, productID)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["GetBySlug"], "GetBySlug")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["SoftDelete"], "SoftDelete")
	assert.True(t, calls["CreateGroup"], "CreateGroup")
	assert.True(t, calls["GetGroupByID"], "GetGroupByID")
	assert.True(t, calls["UpdateGroup"], "UpdateGroup")
	assert.True(t, calls["ListGroups"], "ListGroups")
	assert.True(t, calls["SoftDeleteGroup"], "SoftDeleteGroup")
	assert.True(t, calls["UpsertPricing"], "UpsertPricing")
	assert.True(t, calls["GetPricing"], "GetPricing")
	assert.True(t, calls["ListPricing"], "ListPricing")
	assert.True(t, calls["DeletePricing"], "DeletePricing")
	assert.True(t, calls["ListOptionGroups"], "ListOptionGroups")
	assert.True(t, calls["ListOptions"], "ListOptions")
	assert.True(t, calls["ListOptionValues"], "ListOptionValues")
	assert.True(t, calls["DecrementStock"], "DecrementStock")

	var z mocks.MockProductRepo
	{
		var ctx context.Context
		var pr *domain.Product
		z.Create(ctx, pr)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var slug string
		z.GetBySlug(ctx, slug)
	}
	{
		var ctx context.Context
		var pr *domain.Product
		z.Update(ctx, pr)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		z.SoftDelete(ctx, id)
	}
	{
		var ctx context.Context
		var g *domain.ProductGroup
		z.CreateGroup(ctx, g)
	}
	{
		var ctx context.Context
		var id int64
		z.GetGroupByID(ctx, id)
	}
	{
		var ctx context.Context
		var g *domain.ProductGroup
		z.UpdateGroup(ctx, g)
	}
	{
		var ctx context.Context
		var includeHidden bool
		z.ListGroups(ctx, includeHidden)
	}
	{
		var ctx context.Context
		var id int64
		z.SoftDeleteGroup(ctx, id)
	}
	{
		var ctx context.Context
		var pp *domain.ProductPricing
		z.UpsertPricing(ctx, pp)
	}
	{
		var ctx context.Context
		var productID int64
		var cycle domain.BillingCycle
		z.GetPricing(ctx, productID, cycle)
	}
	{
		var ctx context.Context
		var productID int64
		z.ListPricing(ctx, productID)
	}
	{
		var ctx context.Context
		var productID int64
		var cycle domain.BillingCycle
		z.DeletePricing(ctx, productID, cycle)
	}
	{
		var ctx context.Context
		z.ListOptionGroups(ctx)
	}
	{
		var ctx context.Context
		var groupID int64
		z.ListOptions(ctx, groupID)
	}
	{
		var ctx context.Context
		var optionID int64
		z.ListOptionValues(ctx, optionID)
	}
	{
		var ctx context.Context
		var productID int64
		z.DecrementStock(ctx, productID)
	}
}

func TestGenerated_MockCouponRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockCouponRepo{
		CreateFn:  func(ctx context.Context, c *domain.Coupon) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Coupon, r1 error) { calls["GetByID"] = true; return },
		GetByCodeFn: func(ctx context.Context, code string) (r0 *domain.Coupon, r1 error) {
			calls["GetByCode"] = true
			return
		},
		UpdateFn: func(ctx context.Context, c *domain.Coupon) (r0 error) { calls["Update"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Coupon, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		DeleteFn:         func(ctx context.Context, id int64) (r0 error) { calls["Delete"] = true; return },
		IncrementUsageFn: func(ctx context.Context, id int64) (r0 error) { calls["IncrementUsage"] = true; return },
	}

	{
		var ctx context.Context
		var c *domain.Coupon
		m.Create(ctx, c)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var code string
		m.GetByCode(ctx, code)
	}
	{
		var ctx context.Context
		var c *domain.Coupon
		m.Update(ctx, c)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		m.Delete(ctx, id)
	}
	{
		var ctx context.Context
		var id int64
		m.IncrementUsage(ctx, id)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["GetByCode"], "GetByCode")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["Delete"], "Delete")
	assert.True(t, calls["IncrementUsage"], "IncrementUsage")

	var z mocks.MockCouponRepo
	{
		var ctx context.Context
		var c *domain.Coupon
		z.Create(ctx, c)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var code string
		z.GetByCode(ctx, code)
	}
	{
		var ctx context.Context
		var c *domain.Coupon
		z.Update(ctx, c)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		z.Delete(ctx, id)
	}
	{
		var ctx context.Context
		var id int64
		z.IncrementUsage(ctx, id)
	}
}

func TestGenerated_MockOrderRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockOrderRepo{
		CreateFn: func(ctx context.Context, o *domain.Order, items []domain.OrderItem) (r0 error) {
			calls["Create"] = true
			return
		},
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Order, r1 error) { calls["GetByID"] = true; return },
		GetItemsFn: func(ctx context.Context, orderID int64) (r0 []domain.OrderItem, r1 error) {
			calls["GetItems"] = true
			return
		},
		UpdateStatusFn: func(ctx context.Context, id int64, status domain.OrderStatus) (r0 error) {
			calls["UpdateStatus"] = true
			return
		},
		UpdateItemBackRefsFn: func(ctx context.Context, itemID int64, serviceID *int64, domainID *int64) (r0 error) {
			calls["UpdateItemBackRefs"] = true
			return
		},
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Order, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		ListByClientFn: func(ctx context.Context, clientID int64, p ports.ListParams) (r0 []domain.Order, r1 int64, r2 error) {
			calls["ListByClient"] = true
			return
		},
		NextNumberFn: func(ctx context.Context, scope string) (r0 int64, r1 error) { calls["NextNumber"] = true; return },
	}

	{
		var ctx context.Context
		var o *domain.Order
		var items []domain.OrderItem
		m.Create(ctx, o, items)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var orderID int64
		m.GetItems(ctx, orderID)
	}
	{
		var ctx context.Context
		var id int64
		var status domain.OrderStatus
		m.UpdateStatus(ctx, id, status)
	}
	{
		var ctx context.Context
		var itemID int64
		var serviceID *int64
		var domainID *int64
		m.UpdateItemBackRefs(ctx, itemID, serviceID, domainID)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		m.ListByClient(ctx, clientID, p)
	}
	{
		var ctx context.Context
		var scope string
		m.NextNumber(ctx, scope)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["GetItems"], "GetItems")
	assert.True(t, calls["UpdateStatus"], "UpdateStatus")
	assert.True(t, calls["UpdateItemBackRefs"], "UpdateItemBackRefs")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["ListByClient"], "ListByClient")
	assert.True(t, calls["NextNumber"], "NextNumber")

	var z mocks.MockOrderRepo
	{
		var ctx context.Context
		var o *domain.Order
		var items []domain.OrderItem
		z.Create(ctx, o, items)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var orderID int64
		z.GetItems(ctx, orderID)
	}
	{
		var ctx context.Context
		var id int64
		var status domain.OrderStatus
		z.UpdateStatus(ctx, id, status)
	}
	{
		var ctx context.Context
		var itemID int64
		var serviceID *int64
		var domainID *int64
		z.UpdateItemBackRefs(ctx, itemID, serviceID, domainID)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		z.ListByClient(ctx, clientID, p)
	}
	{
		var ctx context.Context
		var scope string
		z.NextNumber(ctx, scope)
	}
}

func TestGenerated_MockInvoiceRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockInvoiceRepo{
		CreateFn: func(ctx context.Context, inv *domain.Invoice, items []domain.InvoiceItem) (r0 error) {
			calls["Create"] = true
			return
		},
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Invoice, r1 error) { calls["GetByID"] = true; return },
		GetByNumberFn: func(ctx context.Context, number string) (r0 *domain.Invoice, r1 error) {
			calls["GetByNumber"] = true
			return
		},
		GetByIDForUpdateFn: func(ctx context.Context, id int64) (r0 *domain.Invoice, r1 error) {
			calls["GetByIDForUpdate"] = true
			return
		},
		GetItemsFn: func(ctx context.Context, invoiceID int64) (r0 []domain.InvoiceItem, r1 error) {
			calls["GetItems"] = true
			return
		},
		AddItemFn: func(ctx context.Context, item *domain.InvoiceItem) (r0 error) { calls["AddItem"] = true; return },
		UpdateFn:  func(ctx context.Context, inv *domain.Invoice) (r0 error) { calls["Update"] = true; return },
		UpdateStatusFn: func(ctx context.Context, id int64, status domain.InvoiceStatus, paidAt *time.Time) (r0 error) {
			calls["UpdateStatus"] = true
			return
		},
		SetPDFObjectKeyFn: func(ctx context.Context, id int64, key string) (r0 error) { calls["SetPDFObjectKey"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Invoice, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		ListByClientFn: func(ctx context.Context, clientID int64, p ports.ListParams) (r0 []domain.Invoice, r1 int64, r2 error) {
			calls["ListByClient"] = true
			return
		},
		ListDueForStatusFn: func(ctx context.Context, status domain.InvoiceStatus, before time.Time) (r0 []domain.Invoice, r1 error) {
			calls["ListDueForStatus"] = true
			return
		},
		NextNumberFn: func(ctx context.Context, scope string) (r0 int64, r1 error) { calls["NextNumber"] = true; return },
	}

	{
		var ctx context.Context
		var inv *domain.Invoice
		var items []domain.InvoiceItem
		m.Create(ctx, inv, items)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var number string
		m.GetByNumber(ctx, number)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByIDForUpdate(ctx, id)
	}
	{
		var ctx context.Context
		var invoiceID int64
		m.GetItems(ctx, invoiceID)
	}
	{
		var ctx context.Context
		var item *domain.InvoiceItem
		m.AddItem(ctx, item)
	}
	{
		var ctx context.Context
		var inv *domain.Invoice
		m.Update(ctx, inv)
	}
	{
		var ctx context.Context
		var id int64
		var status domain.InvoiceStatus
		var paidAt *time.Time
		m.UpdateStatus(ctx, id, status, paidAt)
	}
	{
		var ctx context.Context
		var id int64
		var key string
		m.SetPDFObjectKey(ctx, id, key)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		m.ListByClient(ctx, clientID, p)
	}
	{
		var ctx context.Context
		var status domain.InvoiceStatus
		var before time.Time
		m.ListDueForStatus(ctx, status, before)
	}
	{
		var ctx context.Context
		var scope string
		m.NextNumber(ctx, scope)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["GetByNumber"], "GetByNumber")
	assert.True(t, calls["GetByIDForUpdate"], "GetByIDForUpdate")
	assert.True(t, calls["GetItems"], "GetItems")
	assert.True(t, calls["AddItem"], "AddItem")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["UpdateStatus"], "UpdateStatus")
	assert.True(t, calls["SetPDFObjectKey"], "SetPDFObjectKey")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["ListByClient"], "ListByClient")
	assert.True(t, calls["ListDueForStatus"], "ListDueForStatus")
	assert.True(t, calls["NextNumber"], "NextNumber")

	var z mocks.MockInvoiceRepo
	{
		var ctx context.Context
		var inv *domain.Invoice
		var items []domain.InvoiceItem
		z.Create(ctx, inv, items)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var number string
		z.GetByNumber(ctx, number)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByIDForUpdate(ctx, id)
	}
	{
		var ctx context.Context
		var invoiceID int64
		z.GetItems(ctx, invoiceID)
	}
	{
		var ctx context.Context
		var item *domain.InvoiceItem
		z.AddItem(ctx, item)
	}
	{
		var ctx context.Context
		var inv *domain.Invoice
		z.Update(ctx, inv)
	}
	{
		var ctx context.Context
		var id int64
		var status domain.InvoiceStatus
		var paidAt *time.Time
		z.UpdateStatus(ctx, id, status, paidAt)
	}
	{
		var ctx context.Context
		var id int64
		var key string
		z.SetPDFObjectKey(ctx, id, key)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		z.ListByClient(ctx, clientID, p)
	}
	{
		var ctx context.Context
		var status domain.InvoiceStatus
		var before time.Time
		z.ListDueForStatus(ctx, status, before)
	}
	{
		var ctx context.Context
		var scope string
		z.NextNumber(ctx, scope)
	}
}

func TestGenerated_MockTransactionRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockTransactionRepo{
		CreateFn: func(ctx context.Context, t *domain.Transaction) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Transaction, r1 error) {
			calls["GetByID"] = true
			return
		},
		GetByMerchantOrderIDFn: func(ctx context.Context, merchantOrderID string) (r0 *domain.Transaction, r1 error) {
			calls["GetByMerchantOrderID"] = true
			return
		},
		UpdateFn: func(ctx context.Context, t *domain.Transaction) (r0 error) { calls["Update"] = true; return },
		ListByInvoiceFn: func(ctx context.Context, invoiceID int64) (r0 []domain.Transaction, r1 error) {
			calls["ListByInvoice"] = true
			return
		},
		ListPendingFn: func(ctx context.Context, gateway domain.Gateway, olderThan time.Time) (r0 []domain.Transaction, r1 error) {
			calls["ListPending"] = true
			return
		},
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Transaction, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		NextAttemptFn: func(ctx context.Context, invoiceID int64) (r0 int64, r1 error) {
			calls["NextAttempt"] = true
			return
		},
	}

	{
		var ctx context.Context
		var t *domain.Transaction
		m.Create(ctx, t)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var merchantOrderID string
		m.GetByMerchantOrderID(ctx, merchantOrderID)
	}
	{
		var ctx context.Context
		var t *domain.Transaction
		m.Update(ctx, t)
	}
	{
		var ctx context.Context
		var invoiceID int64
		m.ListByInvoice(ctx, invoiceID)
	}
	{
		var ctx context.Context
		var gateway domain.Gateway
		var olderThan time.Time
		m.ListPending(ctx, gateway, olderThan)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var invoiceID int64
		m.NextAttempt(ctx, invoiceID)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["GetByMerchantOrderID"], "GetByMerchantOrderID")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["ListByInvoice"], "ListByInvoice")
	assert.True(t, calls["ListPending"], "ListPending")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["NextAttempt"], "NextAttempt")

	var z mocks.MockTransactionRepo
	{
		var ctx context.Context
		var t *domain.Transaction
		z.Create(ctx, t)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var merchantOrderID string
		z.GetByMerchantOrderID(ctx, merchantOrderID)
	}
	{
		var ctx context.Context
		var t *domain.Transaction
		z.Update(ctx, t)
	}
	{
		var ctx context.Context
		var invoiceID int64
		z.ListByInvoice(ctx, invoiceID)
	}
	{
		var ctx context.Context
		var gateway domain.Gateway
		var olderThan time.Time
		z.ListPending(ctx, gateway, olderThan)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var invoiceID int64
		z.NextAttempt(ctx, invoiceID)
	}
}

func TestGenerated_MockCreditRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockCreditRepo{
		ListByClientFn: func(ctx context.Context, clientID int64, p ports.ListParams) (r0 []domain.CreditLedgerEntry, r1 int64, r2 error) {
			calls["ListByClient"] = true
			return
		},
	}

	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		m.ListByClient(ctx, clientID, p)
	}

	assert.True(t, calls["ListByClient"], "ListByClient")

	var z mocks.MockCreditRepo
	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		z.ListByClient(ctx, clientID, p)
	}
}

func TestGenerated_MockServiceRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockServiceRepo{
		CreateFn:  func(ctx context.Context, s *domain.Service) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Service, r1 error) { calls["GetByID"] = true; return },
		UpdateFn:  func(ctx context.Context, s *domain.Service) (r0 error) { calls["Update"] = true; return },
		UpdateStatusFn: func(ctx context.Context, id int64, status domain.ServiceStatus) (r0 error) {
			calls["UpdateStatus"] = true
			return
		},
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Service, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		ListByClientFn: func(ctx context.Context, clientID int64, p ports.ListParams) (r0 []domain.Service, r1 int64, r2 error) {
			calls["ListByClient"] = true
			return
		},
		ListRenewalsDueFn: func(ctx context.Context, before time.Time) (r0 []domain.Service, r1 error) {
			calls["ListRenewalsDue"] = true
			return
		},
		CountByServerFn: func(ctx context.Context, serverID int64) (r0 int64, r1 error) { calls["CountByServer"] = true; return },
	}

	{
		var ctx context.Context
		var s *domain.Service
		m.Create(ctx, s)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var s *domain.Service
		m.Update(ctx, s)
	}
	{
		var ctx context.Context
		var id int64
		var status domain.ServiceStatus
		m.UpdateStatus(ctx, id, status)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		m.ListByClient(ctx, clientID, p)
	}
	{
		var ctx context.Context
		var before time.Time
		m.ListRenewalsDue(ctx, before)
	}
	{
		var ctx context.Context
		var serverID int64
		m.CountByServer(ctx, serverID)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["UpdateStatus"], "UpdateStatus")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["ListByClient"], "ListByClient")
	assert.True(t, calls["ListRenewalsDue"], "ListRenewalsDue")
	assert.True(t, calls["CountByServer"], "CountByServer")

	var z mocks.MockServiceRepo
	{
		var ctx context.Context
		var s *domain.Service
		z.Create(ctx, s)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var s *domain.Service
		z.Update(ctx, s)
	}
	{
		var ctx context.Context
		var id int64
		var status domain.ServiceStatus
		z.UpdateStatus(ctx, id, status)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		z.ListByClient(ctx, clientID, p)
	}
	{
		var ctx context.Context
		var before time.Time
		z.ListRenewalsDue(ctx, before)
	}
	{
		var ctx context.Context
		var serverID int64
		z.CountByServer(ctx, serverID)
	}
}

func TestGenerated_MockServerRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockServerRepo{
		CreateFn:  func(ctx context.Context, s *domain.Server) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Server, r1 error) { calls["GetByID"] = true; return },
		UpdateFn:  func(ctx context.Context, s *domain.Server) (r0 error) { calls["Update"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Server, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		DeleteFn:      func(ctx context.Context, id int64) (r0 error) { calls["Delete"] = true; return },
		CreateGroupFn: func(ctx context.Context, g *domain.ServerGroup) (r0 error) { calls["CreateGroup"] = true; return },
		GetGroupByIDFn: func(ctx context.Context, id int64) (r0 *domain.ServerGroup, r1 error) {
			calls["GetGroupByID"] = true
			return
		},
		UpdateGroupFn: func(ctx context.Context, g *domain.ServerGroup) (r0 error) { calls["UpdateGroup"] = true; return },
		ListGroupsFn:  func(ctx context.Context) (r0 []domain.ServerGroup, r1 error) { calls["ListGroups"] = true; return },
		DeleteGroupFn: func(ctx context.Context, id int64) (r0 error) { calls["DeleteGroup"] = true; return },
		PickServerFn: func(ctx context.Context, groupID int64) (r0 *domain.Server, r1 error) {
			calls["PickServer"] = true
			return
		},
	}

	{
		var ctx context.Context
		var s *domain.Server
		m.Create(ctx, s)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var s *domain.Server
		m.Update(ctx, s)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		m.Delete(ctx, id)
	}
	{
		var ctx context.Context
		var g *domain.ServerGroup
		m.CreateGroup(ctx, g)
	}
	{
		var ctx context.Context
		var id int64
		m.GetGroupByID(ctx, id)
	}
	{
		var ctx context.Context
		var g *domain.ServerGroup
		m.UpdateGroup(ctx, g)
	}
	{
		var ctx context.Context
		m.ListGroups(ctx)
	}
	{
		var ctx context.Context
		var id int64
		m.DeleteGroup(ctx, id)
	}
	{
		var ctx context.Context
		var groupID int64
		m.PickServer(ctx, groupID)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["Delete"], "Delete")
	assert.True(t, calls["CreateGroup"], "CreateGroup")
	assert.True(t, calls["GetGroupByID"], "GetGroupByID")
	assert.True(t, calls["UpdateGroup"], "UpdateGroup")
	assert.True(t, calls["ListGroups"], "ListGroups")
	assert.True(t, calls["DeleteGroup"], "DeleteGroup")
	assert.True(t, calls["PickServer"], "PickServer")

	var z mocks.MockServerRepo
	{
		var ctx context.Context
		var s *domain.Server
		z.Create(ctx, s)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var s *domain.Server
		z.Update(ctx, s)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		z.Delete(ctx, id)
	}
	{
		var ctx context.Context
		var g *domain.ServerGroup
		z.CreateGroup(ctx, g)
	}
	{
		var ctx context.Context
		var id int64
		z.GetGroupByID(ctx, id)
	}
	{
		var ctx context.Context
		var g *domain.ServerGroup
		z.UpdateGroup(ctx, g)
	}
	{
		var ctx context.Context
		z.ListGroups(ctx)
	}
	{
		var ctx context.Context
		var id int64
		z.DeleteGroup(ctx, id)
	}
	{
		var ctx context.Context
		var groupID int64
		z.PickServer(ctx, groupID)
	}
}

func TestGenerated_MockDomainRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockDomainRepo{
		CreateFn:  func(ctx context.Context, d *domain.Domain) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Domain, r1 error) { calls["GetByID"] = true; return },
		GetByNameFn: func(ctx context.Context, name string) (r0 *domain.Domain, r1 error) {
			calls["GetByName"] = true
			return
		},
		UpdateFn: func(ctx context.Context, d *domain.Domain) (r0 error) { calls["Update"] = true; return },
		UpdateStatusFn: func(ctx context.Context, id int64, status domain.DomainStatus) (r0 error) {
			calls["UpdateStatus"] = true
			return
		},
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Domain, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		ListByClientFn: func(ctx context.Context, clientID int64, p ports.ListParams) (r0 []domain.Domain, r1 int64, r2 error) {
			calls["ListByClient"] = true
			return
		},
		ListRenewalsDueFn: func(ctx context.Context, before time.Time) (r0 []domain.Domain, r1 error) {
			calls["ListRenewalsDue"] = true
			return
		},
		ListForSyncFn: func(ctx context.Context, limit int) (r0 []domain.Domain, r1 error) {
			calls["ListForSync"] = true
			return
		},
	}

	{
		var ctx context.Context
		var d *domain.Domain
		m.Create(ctx, d)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var name string
		m.GetByName(ctx, name)
	}
	{
		var ctx context.Context
		var d *domain.Domain
		m.Update(ctx, d)
	}
	{
		var ctx context.Context
		var id int64
		var status domain.DomainStatus
		m.UpdateStatus(ctx, id, status)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		m.ListByClient(ctx, clientID, p)
	}
	{
		var ctx context.Context
		var before time.Time
		m.ListRenewalsDue(ctx, before)
	}
	{
		var ctx context.Context
		var limit int
		m.ListForSync(ctx, limit)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["GetByName"], "GetByName")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["UpdateStatus"], "UpdateStatus")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["ListByClient"], "ListByClient")
	assert.True(t, calls["ListRenewalsDue"], "ListRenewalsDue")
	assert.True(t, calls["ListForSync"], "ListForSync")

	var z mocks.MockDomainRepo
	{
		var ctx context.Context
		var d *domain.Domain
		z.Create(ctx, d)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var name string
		z.GetByName(ctx, name)
	}
	{
		var ctx context.Context
		var d *domain.Domain
		z.Update(ctx, d)
	}
	{
		var ctx context.Context
		var id int64
		var status domain.DomainStatus
		z.UpdateStatus(ctx, id, status)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		z.ListByClient(ctx, clientID, p)
	}
	{
		var ctx context.Context
		var before time.Time
		z.ListRenewalsDue(ctx, before)
	}
	{
		var ctx context.Context
		var limit int
		z.ListForSync(ctx, limit)
	}
}

func TestGenerated_MockRegistrarRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockRegistrarRepo{
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Registrar, r1 error) { calls["GetByID"] = true; return },
		GetByNameFn: func(ctx context.Context, name string) (r0 *domain.Registrar, r1 error) {
			calls["GetByName"] = true
			return
		},
		UpdateFn: func(ctx context.Context, r *domain.Registrar) (r0 error) { calls["Update"] = true; return },
		ListFn:   func(ctx context.Context) (r0 []domain.Registrar, r1 error) { calls["List"] = true; return },
	}

	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var name string
		m.GetByName(ctx, name)
	}
	{
		var ctx context.Context
		var r *domain.Registrar
		m.Update(ctx, r)
	}
	{
		var ctx context.Context
		m.List(ctx)
	}

	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["GetByName"], "GetByName")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["List"], "List")

	var z mocks.MockRegistrarRepo
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var name string
		z.GetByName(ctx, name)
	}
	{
		var ctx context.Context
		var r *domain.Registrar
		z.Update(ctx, r)
	}
	{
		var ctx context.Context
		z.List(ctx)
	}
}

func TestGenerated_MockTicketRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockTicketRepo{
		CreateFn:  func(ctx context.Context, t *domain.Ticket) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Ticket, r1 error) { calls["GetByID"] = true; return },
		UpdateFn:  func(ctx context.Context, t *domain.Ticket) (r0 error) { calls["Update"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Ticket, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		ListByClientFn: func(ctx context.Context, clientID int64, p ports.ListParams) (r0 []domain.Ticket, r1 int64, r2 error) {
			calls["ListByClient"] = true
			return
		},
		NextNumberFn: func(ctx context.Context, scope string) (r0 int64, r1 error) { calls["NextNumber"] = true; return },
		AddReplyFn:   func(ctx context.Context, r *domain.TicketReply) (r0 error) { calls["AddReply"] = true; return },
		ListRepliesFn: func(ctx context.Context, ticketID int64, includeInternal bool) (r0 []domain.TicketReply, r1 error) {
			calls["ListReplies"] = true
			return
		},
		CreateDepartmentFn: func(ctx context.Context, d *domain.TicketDepartment) (r0 error) {
			calls["CreateDepartment"] = true
			return
		},
		GetDepartmentByIDFn: func(ctx context.Context, id int64) (r0 *domain.TicketDepartment, r1 error) {
			calls["GetDepartmentByID"] = true
			return
		},
		UpdateDepartmentFn: func(ctx context.Context, d *domain.TicketDepartment) (r0 error) {
			calls["UpdateDepartment"] = true
			return
		},
		ListDepartmentsFn: func(ctx context.Context, activeOnly bool) (r0 []domain.TicketDepartment, r1 error) {
			calls["ListDepartments"] = true
			return
		},
		DeleteDepartmentFn: func(ctx context.Context, id int64) (r0 error) { calls["DeleteDepartment"] = true; return },
	}

	{
		var ctx context.Context
		var t *domain.Ticket
		m.Create(ctx, t)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var t *domain.Ticket
		m.Update(ctx, t)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		m.ListByClient(ctx, clientID, p)
	}
	{
		var ctx context.Context
		var scope string
		m.NextNumber(ctx, scope)
	}
	{
		var ctx context.Context
		var r *domain.TicketReply
		m.AddReply(ctx, r)
	}
	{
		var ctx context.Context
		var ticketID int64
		var includeInternal bool
		m.ListReplies(ctx, ticketID, includeInternal)
	}
	{
		var ctx context.Context
		var d *domain.TicketDepartment
		m.CreateDepartment(ctx, d)
	}
	{
		var ctx context.Context
		var id int64
		m.GetDepartmentByID(ctx, id)
	}
	{
		var ctx context.Context
		var d *domain.TicketDepartment
		m.UpdateDepartment(ctx, d)
	}
	{
		var ctx context.Context
		var activeOnly bool
		m.ListDepartments(ctx, activeOnly)
	}
	{
		var ctx context.Context
		var id int64
		m.DeleteDepartment(ctx, id)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["ListByClient"], "ListByClient")
	assert.True(t, calls["NextNumber"], "NextNumber")
	assert.True(t, calls["AddReply"], "AddReply")
	assert.True(t, calls["ListReplies"], "ListReplies")
	assert.True(t, calls["CreateDepartment"], "CreateDepartment")
	assert.True(t, calls["GetDepartmentByID"], "GetDepartmentByID")
	assert.True(t, calls["UpdateDepartment"], "UpdateDepartment")
	assert.True(t, calls["ListDepartments"], "ListDepartments")
	assert.True(t, calls["DeleteDepartment"], "DeleteDepartment")

	var z mocks.MockTicketRepo
	{
		var ctx context.Context
		var t *domain.Ticket
		z.Create(ctx, t)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var t *domain.Ticket
		z.Update(ctx, t)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var clientID int64
		var p ports.ListParams
		z.ListByClient(ctx, clientID, p)
	}
	{
		var ctx context.Context
		var scope string
		z.NextNumber(ctx, scope)
	}
	{
		var ctx context.Context
		var r *domain.TicketReply
		z.AddReply(ctx, r)
	}
	{
		var ctx context.Context
		var ticketID int64
		var includeInternal bool
		z.ListReplies(ctx, ticketID, includeInternal)
	}
	{
		var ctx context.Context
		var d *domain.TicketDepartment
		z.CreateDepartment(ctx, d)
	}
	{
		var ctx context.Context
		var id int64
		z.GetDepartmentByID(ctx, id)
	}
	{
		var ctx context.Context
		var d *domain.TicketDepartment
		z.UpdateDepartment(ctx, d)
	}
	{
		var ctx context.Context
		var activeOnly bool
		z.ListDepartments(ctx, activeOnly)
	}
	{
		var ctx context.Context
		var id int64
		z.DeleteDepartment(ctx, id)
	}
}

func TestGenerated_MockEmailTemplateRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockEmailTemplateRepo{
		GetFn: func(ctx context.Context, key string, locale string) (r0 *domain.EmailTemplate, r1 error) {
			calls["Get"] = true
			return
		},
		UpsertFn: func(ctx context.Context, t *domain.EmailTemplate) (r0 error) { calls["Upsert"] = true; return },
		ListFn:   func(ctx context.Context) (r0 []domain.EmailTemplate, r1 error) { calls["List"] = true; return },
		DeleteFn: func(ctx context.Context, key string, locale string) (r0 error) { calls["Delete"] = true; return },
	}

	{
		var ctx context.Context
		var key string
		var locale string
		m.Get(ctx, key, locale)
	}
	{
		var ctx context.Context
		var t *domain.EmailTemplate
		m.Upsert(ctx, t)
	}
	{
		var ctx context.Context
		m.List(ctx)
	}
	{
		var ctx context.Context
		var key string
		var locale string
		m.Delete(ctx, key, locale)
	}

	assert.True(t, calls["Get"], "Get")
	assert.True(t, calls["Upsert"], "Upsert")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["Delete"], "Delete")

	var z mocks.MockEmailTemplateRepo
	{
		var ctx context.Context
		var key string
		var locale string
		z.Get(ctx, key, locale)
	}
	{
		var ctx context.Context
		var t *domain.EmailTemplate
		z.Upsert(ctx, t)
	}
	{
		var ctx context.Context
		z.List(ctx)
	}
	{
		var ctx context.Context
		var key string
		var locale string
		z.Delete(ctx, key, locale)
	}
}

func TestGenerated_MockEmailLogRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockEmailLogRepo{
		CreateFn: func(ctx context.Context, e *domain.EmailLogEntry) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.EmailLogEntry, r1 error) {
			calls["GetByID"] = true
			return
		},
		MarkSentFn:   func(ctx context.Context, id int64, at time.Time) (r0 error) { calls["MarkSent"] = true; return },
		MarkFailedFn: func(ctx context.Context, id int64, errMsg string) (r0 error) { calls["MarkFailed"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.EmailLogEntry, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
	}

	{
		var ctx context.Context
		var e *domain.EmailLogEntry
		m.Create(ctx, e)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var id int64
		var at time.Time
		m.MarkSent(ctx, id, at)
	}
	{
		var ctx context.Context
		var id int64
		var errMsg string
		m.MarkFailed(ctx, id, errMsg)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["MarkSent"], "MarkSent")
	assert.True(t, calls["MarkFailed"], "MarkFailed")
	assert.True(t, calls["List"], "List")

	var z mocks.MockEmailLogRepo
	{
		var ctx context.Context
		var e *domain.EmailLogEntry
		z.Create(ctx, e)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var id int64
		var at time.Time
		z.MarkSent(ctx, id, at)
	}
	{
		var ctx context.Context
		var id int64
		var errMsg string
		z.MarkFailed(ctx, id, errMsg)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
}

func TestGenerated_MockSettingsRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockSettingsRepo{
		GetStringFn: func(ctx context.Context, key string, def string) (r0 string, r1 error) {
			calls["GetString"] = true
			return
		},
		GetIntFn:  func(ctx context.Context, key string, def int) (r0 int, r1 error) { calls["GetInt"] = true; return },
		GetBoolFn: func(ctx context.Context, key string, def bool) (r0 bool, r1 error) { calls["GetBool"] = true; return },
		GetJSONFn: func(ctx context.Context, key string, out any) (r0 error) { calls["GetJSON"] = true; return },
		SetFn:     func(ctx context.Context, key string, value any) (r0 error) { calls["Set"] = true; return },
		AllFn:     func(ctx context.Context) (r0 []domain.Setting, r1 error) { calls["All"] = true; return },
	}

	{
		var ctx context.Context
		var key string
		var def string
		m.GetString(ctx, key, def)
	}
	{
		var ctx context.Context
		var key string
		var def int
		m.GetInt(ctx, key, def)
	}
	{
		var ctx context.Context
		var key string
		var def bool
		m.GetBool(ctx, key, def)
	}
	{
		var ctx context.Context
		var key string
		var out any
		m.GetJSON(ctx, key, out)
	}
	{
		var ctx context.Context
		var key string
		var value any
		m.Set(ctx, key, value)
	}
	{
		var ctx context.Context
		m.All(ctx)
	}

	assert.True(t, calls["GetString"], "GetString")
	assert.True(t, calls["GetInt"], "GetInt")
	assert.True(t, calls["GetBool"], "GetBool")
	assert.True(t, calls["GetJSON"], "GetJSON")
	assert.True(t, calls["Set"], "Set")
	assert.True(t, calls["All"], "All")

	var z mocks.MockSettingsRepo
	{
		var ctx context.Context
		var key string
		var def string
		z.GetString(ctx, key, def)
	}
	{
		var ctx context.Context
		var key string
		var def int
		z.GetInt(ctx, key, def)
	}
	{
		var ctx context.Context
		var key string
		var def bool
		z.GetBool(ctx, key, def)
	}
	{
		var ctx context.Context
		var key string
		var out any
		z.GetJSON(ctx, key, out)
	}
	{
		var ctx context.Context
		var key string
		var value any
		z.Set(ctx, key, value)
	}
	{
		var ctx context.Context
		z.All(ctx)
	}
}

func TestGenerated_MockAuditRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockAuditRepo{
		CreateFn: func(ctx context.Context, a *domain.AuditLog) (r0 error) { calls["Create"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.AuditLog, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
	}

	{
		var ctx context.Context
		var a *domain.AuditLog
		m.Create(ctx, a)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["List"], "List")

	var z mocks.MockAuditRepo
	{
		var ctx context.Context
		var a *domain.AuditLog
		z.Create(ctx, a)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
}

func TestGenerated_MockIntegrationLogRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockIntegrationLogRepo{
		CreateFn: func(ctx context.Context, l *domain.IntegrationLog) (r0 error) { calls["Create"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.IntegrationLog, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
	}

	{
		var ctx context.Context
		var l *domain.IntegrationLog
		m.Create(ctx, l)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["List"], "List")

	var z mocks.MockIntegrationLogRepo
	{
		var ctx context.Context
		var l *domain.IntegrationLog
		z.Create(ctx, l)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
}

func TestGenerated_MockDashboardRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockDashboardRepo{
		StatsFn: func(ctx context.Context) (r0 *ports.DashboardStats, r1 error) { calls["Stats"] = true; return },
		RevenueFn: func(ctx context.Context, from time.Time, to time.Time, groupBy string) (r0 []ports.RevenuePoint, r1 error) {
			calls["Revenue"] = true
			return
		},
		OrdersReportFn: func(ctx context.Context, from time.Time, to time.Time) (r0 []ports.RevenuePoint, r1 error) {
			calls["OrdersReport"] = true
			return
		},
		ServicesReportFn: func(ctx context.Context) (r0 map[string]int64, r1 error) { calls["ServicesReport"] = true; return },
	}

	{
		var ctx context.Context
		m.Stats(ctx)
	}
	{
		var ctx context.Context
		var from time.Time
		var to time.Time
		var groupBy string
		m.Revenue(ctx, from, to, groupBy)
	}
	{
		var ctx context.Context
		var from time.Time
		var to time.Time
		m.OrdersReport(ctx, from, to)
	}
	{
		var ctx context.Context
		m.ServicesReport(ctx)
	}

	assert.True(t, calls["Stats"], "Stats")
	assert.True(t, calls["Revenue"], "Revenue")
	assert.True(t, calls["OrdersReport"], "OrdersReport")
	assert.True(t, calls["ServicesReport"], "ServicesReport")

	var z mocks.MockDashboardRepo
	{
		var ctx context.Context
		z.Stats(ctx)
	}
	{
		var ctx context.Context
		var from time.Time
		var to time.Time
		var groupBy string
		z.Revenue(ctx, from, to, groupBy)
	}
	{
		var ctx context.Context
		var from time.Time
		var to time.Time
		z.OrdersReport(ctx, from, to)
	}
	{
		var ctx context.Context
		z.ServicesReport(ctx)
	}
}

func TestGenerated_MockPaymentGateway(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockPaymentGateway{
		GetPaymentMethodsFn: func(ctx context.Context, amount int64) (r0 []ports.PaymentMethod, r1 error) {
			calls["GetPaymentMethods"] = true
			return
		},
		CreateTransactionFn: func(ctx context.Context, req ports.CreateTxRequest) (r0 *ports.CreateTxResult, r1 error) {
			calls["CreateTransaction"] = true
			return
		},
		CheckTransactionFn: func(ctx context.Context, merchantOrderID string) (r0 *ports.TxStatus, r1 error) {
			calls["CheckTransaction"] = true
			return
		},
		VerifyCallbackSignatureFn: func(p ports.CallbackPayload) (r0 bool) { calls["VerifyCallbackSignature"] = true; return },
	}

	{
		var ctx context.Context
		var amount int64
		m.GetPaymentMethods(ctx, amount)
	}
	{
		var ctx context.Context
		var req ports.CreateTxRequest
		m.CreateTransaction(ctx, req)
	}
	{
		var ctx context.Context
		var merchantOrderID string
		m.CheckTransaction(ctx, merchantOrderID)
	}
	{
		var p ports.CallbackPayload
		m.VerifyCallbackSignature(p)
	}

	assert.True(t, calls["GetPaymentMethods"], "GetPaymentMethods")
	assert.True(t, calls["CreateTransaction"], "CreateTransaction")
	assert.True(t, calls["CheckTransaction"], "CheckTransaction")
	assert.True(t, calls["VerifyCallbackSignature"], "VerifyCallbackSignature")

	var z mocks.MockPaymentGateway
	{
		var ctx context.Context
		var amount int64
		z.GetPaymentMethods(ctx, amount)
	}
	{
		var ctx context.Context
		var req ports.CreateTxRequest
		z.CreateTransaction(ctx, req)
	}
	{
		var ctx context.Context
		var merchantOrderID string
		z.CheckTransaction(ctx, merchantOrderID)
	}
	{
		var p ports.CallbackPayload
		z.VerifyCallbackSignature(p)
	}
}

func TestGenerated_MockServerModule(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockServerModule{
		NameFn: func() (r0 string) { calls["Name"] = true; return },
		CreateFn: func(ctx context.Context, s ports.ServerConfig, a ports.CreateAccountParams) (r0 *ports.AccountResult, r1 error) {
			calls["Create"] = true
			return
		},
		SuspendFn: func(ctx context.Context, s ports.ServerConfig, username string, reason string) (r0 error) {
			calls["Suspend"] = true
			return
		},
		UnsuspendFn: func(ctx context.Context, s ports.ServerConfig, username string) (r0 error) {
			calls["Unsuspend"] = true
			return
		},
		TerminateFn: func(ctx context.Context, s ports.ServerConfig, username string) (r0 error) {
			calls["Terminate"] = true
			return
		},
		ChangePackageFn: func(ctx context.Context, s ports.ServerConfig, username string, pkg string) (r0 error) {
			calls["ChangePackage"] = true
			return
		},
		ChangePasswordFn: func(ctx context.Context, s ports.ServerConfig, username string, password string) (r0 error) {
			calls["ChangePassword"] = true
			return
		},
		AccountInfoFn: func(ctx context.Context, s ports.ServerConfig, username string) (r0 *ports.AccountInfo, r1 error) {
			calls["AccountInfo"] = true
			return
		},
		SSOURLFn: func(ctx context.Context, s ports.ServerConfig, username string) (r0 string, r1 error) {
			calls["SSOURL"] = true
			return
		},
	}

	{
		m.Name()
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var a ports.CreateAccountParams
		m.Create(ctx, s, a)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		var reason string
		m.Suspend(ctx, s, username, reason)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		m.Unsuspend(ctx, s, username)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		m.Terminate(ctx, s, username)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		var pkg string
		m.ChangePackage(ctx, s, username, pkg)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		var password string
		m.ChangePassword(ctx, s, username, password)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		m.AccountInfo(ctx, s, username)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		m.SSOURL(ctx, s, username)
	}

	assert.True(t, calls["Name"], "Name")
	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["Suspend"], "Suspend")
	assert.True(t, calls["Unsuspend"], "Unsuspend")
	assert.True(t, calls["Terminate"], "Terminate")
	assert.True(t, calls["ChangePackage"], "ChangePackage")
	assert.True(t, calls["ChangePassword"], "ChangePassword")
	assert.True(t, calls["AccountInfo"], "AccountInfo")
	assert.True(t, calls["SSOURL"], "SSOURL")

	var z mocks.MockServerModule
	{
		z.Name()
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var a ports.CreateAccountParams
		z.Create(ctx, s, a)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		var reason string
		z.Suspend(ctx, s, username, reason)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		z.Unsuspend(ctx, s, username)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		z.Terminate(ctx, s, username)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		var pkg string
		z.ChangePackage(ctx, s, username, pkg)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		var password string
		z.ChangePassword(ctx, s, username, password)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		z.AccountInfo(ctx, s, username)
	}
	{
		var ctx context.Context
		var s ports.ServerConfig
		var username string
		z.SSOURL(ctx, s, username)
	}
}

func TestGenerated_MockRegistrarModule(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockRegistrarModule{
		CheckAvailabilityFn: func(ctx context.Context, names []string) (r0 []ports.DomainAvailability, r1 error) {
			calls["CheckAvailability"] = true
			return
		},
		RegisterFn: func(ctx context.Context, req ports.RegisterDomainRequest) (r0 *ports.DomainResult, r1 error) {
			calls["Register"] = true
			return
		},
		TransferFn: func(ctx context.Context, req ports.TransferDomainRequest) (r0 *ports.DomainResult, r1 error) {
			calls["Transfer"] = true
			return
		},
		RenewFn: func(ctx context.Context, name string, years int) (r0 *ports.DomainResult, r1 error) {
			calls["Renew"] = true
			return
		},
		GetNameserversFn: func(ctx context.Context, name string) (r0 []string, r1 error) { calls["GetNameservers"] = true; return },
		UpdateNameserversFn: func(ctx context.Context, name string, ns []string) (r0 error) {
			calls["UpdateNameservers"] = true
			return
		},
		GetContactFn: func(ctx context.Context, name string) (r0 *ports.RegistrantContact, r1 error) {
			calls["GetContact"] = true
			return
		},
		UpdateContactFn: func(ctx context.Context, name string, c ports.RegistrantContact) (r0 error) {
			calls["UpdateContact"] = true
			return
		},
		GetEPPCodeFn: func(ctx context.Context, name string) (r0 string, r1 error) { calls["GetEPPCode"] = true; return },
		GetDNSRecordsFn: func(ctx context.Context, name string) (r0 []ports.DNSRecord, r1 error) {
			calls["GetDNSRecords"] = true
			return
		},
		UpdateDNSRecordsFn: func(ctx context.Context, name string, recs []ports.DNSRecord) (r0 error) {
			calls["UpdateDNSRecords"] = true
			return
		},
		SyncDomainFn: func(ctx context.Context, name string) (r0 *ports.DomainSyncInfo, r1 error) {
			calls["SyncDomain"] = true
			return
		},
	}

	{
		var ctx context.Context
		var names []string
		m.CheckAvailability(ctx, names)
	}
	{
		var ctx context.Context
		var req ports.RegisterDomainRequest
		m.Register(ctx, req)
	}
	{
		var ctx context.Context
		var req ports.TransferDomainRequest
		m.Transfer(ctx, req)
	}
	{
		var ctx context.Context
		var name string
		var years int
		m.Renew(ctx, name, years)
	}
	{
		var ctx context.Context
		var name string
		m.GetNameservers(ctx, name)
	}
	{
		var ctx context.Context
		var name string
		var ns []string
		m.UpdateNameservers(ctx, name, ns)
	}
	{
		var ctx context.Context
		var name string
		m.GetContact(ctx, name)
	}
	{
		var ctx context.Context
		var name string
		var c ports.RegistrantContact
		m.UpdateContact(ctx, name, c)
	}
	{
		var ctx context.Context
		var name string
		m.GetEPPCode(ctx, name)
	}
	{
		var ctx context.Context
		var name string
		m.GetDNSRecords(ctx, name)
	}
	{
		var ctx context.Context
		var name string
		var recs []ports.DNSRecord
		m.UpdateDNSRecords(ctx, name, recs)
	}
	{
		var ctx context.Context
		var name string
		m.SyncDomain(ctx, name)
	}

	assert.True(t, calls["CheckAvailability"], "CheckAvailability")
	assert.True(t, calls["Register"], "Register")
	assert.True(t, calls["Transfer"], "Transfer")
	assert.True(t, calls["Renew"], "Renew")
	assert.True(t, calls["GetNameservers"], "GetNameservers")
	assert.True(t, calls["UpdateNameservers"], "UpdateNameservers")
	assert.True(t, calls["GetContact"], "GetContact")
	assert.True(t, calls["UpdateContact"], "UpdateContact")
	assert.True(t, calls["GetEPPCode"], "GetEPPCode")
	assert.True(t, calls["GetDNSRecords"], "GetDNSRecords")
	assert.True(t, calls["UpdateDNSRecords"], "UpdateDNSRecords")
	assert.True(t, calls["SyncDomain"], "SyncDomain")

	var z mocks.MockRegistrarModule
	{
		var ctx context.Context
		var names []string
		z.CheckAvailability(ctx, names)
	}
	{
		var ctx context.Context
		var req ports.RegisterDomainRequest
		z.Register(ctx, req)
	}
	{
		var ctx context.Context
		var req ports.TransferDomainRequest
		z.Transfer(ctx, req)
	}
	{
		var ctx context.Context
		var name string
		var years int
		z.Renew(ctx, name, years)
	}
	{
		var ctx context.Context
		var name string
		z.GetNameservers(ctx, name)
	}
	{
		var ctx context.Context
		var name string
		var ns []string
		z.UpdateNameservers(ctx, name, ns)
	}
	{
		var ctx context.Context
		var name string
		z.GetContact(ctx, name)
	}
	{
		var ctx context.Context
		var name string
		var c ports.RegistrantContact
		z.UpdateContact(ctx, name, c)
	}
	{
		var ctx context.Context
		var name string
		z.GetEPPCode(ctx, name)
	}
	{
		var ctx context.Context
		var name string
		z.GetDNSRecords(ctx, name)
	}
	{
		var ctx context.Context
		var name string
		var recs []ports.DNSRecord
		z.UpdateDNSRecords(ctx, name, recs)
	}
	{
		var ctx context.Context
		var name string
		z.SyncDomain(ctx, name)
	}
}

func TestGenerated_MockAnnouncementRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockAnnouncementRepo{
		CreateFn: func(ctx context.Context, a *domain.Announcement) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.Announcement, r1 error) {
			calls["GetByID"] = true
			return
		},
		GetBySlugFn: func(ctx context.Context, slug string) (r0 *domain.Announcement, r1 error) {
			calls["GetBySlug"] = true
			return
		},
		UpdateFn: func(ctx context.Context, a *domain.Announcement) (r0 error) { calls["Update"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Announcement, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		ListPublishedFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.Announcement, r1 int64, r2 error) {
			calls["ListPublished"] = true
			return
		},
		SoftDeleteFn: func(ctx context.Context, id int64) (r0 error) { calls["SoftDelete"] = true; return },
	}

	{
		var ctx context.Context
		var a *domain.Announcement
		m.Create(ctx, a)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var slug string
		m.GetBySlug(ctx, slug)
	}
	{
		var ctx context.Context
		var a *domain.Announcement
		m.Update(ctx, a)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.ListPublished(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		m.SoftDelete(ctx, id)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["GetBySlug"], "GetBySlug")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["ListPublished"], "ListPublished")
	assert.True(t, calls["SoftDelete"], "SoftDelete")

	var z mocks.MockAnnouncementRepo
	{
		var ctx context.Context
		var a *domain.Announcement
		z.Create(ctx, a)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var slug string
		z.GetBySlug(ctx, slug)
	}
	{
		var ctx context.Context
		var a *domain.Announcement
		z.Update(ctx, a)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.ListPublished(ctx, p)
	}
	{
		var ctx context.Context
		var id int64
		z.SoftDelete(ctx, id)
	}
}

func TestGenerated_MockKnowledgebaseRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockKnowledgebaseRepo{
		CreateCategoryFn: func(ctx context.Context, c *domain.KBCategory) (r0 error) { calls["CreateCategory"] = true; return },
		GetCategoryByIDFn: func(ctx context.Context, id int64) (r0 *domain.KBCategory, r1 error) {
			calls["GetCategoryByID"] = true
			return
		},
		GetCategoryBySlugFn: func(ctx context.Context, slug string) (r0 *domain.KBCategory, r1 error) {
			calls["GetCategoryBySlug"] = true
			return
		},
		UpdateCategoryFn: func(ctx context.Context, c *domain.KBCategory) (r0 error) { calls["UpdateCategory"] = true; return },
		ListCategoriesFn: func(ctx context.Context, includeHidden bool) (r0 []domain.KBCategory, r1 error) {
			calls["ListCategories"] = true
			return
		},
		SoftDeleteCategoryFn: func(ctx context.Context, id int64) (r0 error) { calls["SoftDeleteCategory"] = true; return },
		CountArticlesInCategoryFn: func(ctx context.Context, categoryID int64) (r0 int64, r1 error) {
			calls["CountArticlesInCategory"] = true
			return
		},
		CreateArticleFn: func(ctx context.Context, a *domain.KBArticle) (r0 error) { calls["CreateArticle"] = true; return },
		GetArticleByIDFn: func(ctx context.Context, id int64) (r0 *domain.KBArticle, r1 error) {
			calls["GetArticleByID"] = true
			return
		},
		GetArticleBySlugFn: func(ctx context.Context, slug string) (r0 *domain.KBArticle, r1 error) {
			calls["GetArticleBySlug"] = true
			return
		},
		UpdateArticleFn: func(ctx context.Context, a *domain.KBArticle) (r0 error) { calls["UpdateArticle"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.KBArticle, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		ListPublishedFn: func(ctx context.Context, categoryID int64, p ports.ListParams) (r0 []domain.KBArticle, r1 int64, r2 error) {
			calls["ListPublished"] = true
			return
		},
		SoftDeleteArticleFn: func(ctx context.Context, id int64) (r0 error) { calls["SoftDeleteArticle"] = true; return },
		IncrementViewsFn:    func(ctx context.Context, id int64) (r0 error) { calls["IncrementViews"] = true; return },
	}

	{
		var ctx context.Context
		var c *domain.KBCategory
		m.CreateCategory(ctx, c)
	}
	{
		var ctx context.Context
		var id int64
		m.GetCategoryByID(ctx, id)
	}
	{
		var ctx context.Context
		var slug string
		m.GetCategoryBySlug(ctx, slug)
	}
	{
		var ctx context.Context
		var c *domain.KBCategory
		m.UpdateCategory(ctx, c)
	}
	{
		var ctx context.Context
		var includeHidden bool
		m.ListCategories(ctx, includeHidden)
	}
	{
		var ctx context.Context
		var id int64
		m.SoftDeleteCategory(ctx, id)
	}
	{
		var ctx context.Context
		var categoryID int64
		m.CountArticlesInCategory(ctx, categoryID)
	}
	{
		var ctx context.Context
		var a *domain.KBArticle
		m.CreateArticle(ctx, a)
	}
	{
		var ctx context.Context
		var id int64
		m.GetArticleByID(ctx, id)
	}
	{
		var ctx context.Context
		var slug string
		m.GetArticleBySlug(ctx, slug)
	}
	{
		var ctx context.Context
		var a *domain.KBArticle
		m.UpdateArticle(ctx, a)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		var categoryID int64
		var p ports.ListParams
		m.ListPublished(ctx, categoryID, p)
	}
	{
		var ctx context.Context
		var id int64
		m.SoftDeleteArticle(ctx, id)
	}
	{
		var ctx context.Context
		var id int64
		m.IncrementViews(ctx, id)
	}

	assert.True(t, calls["CreateCategory"], "CreateCategory")
	assert.True(t, calls["GetCategoryByID"], "GetCategoryByID")
	assert.True(t, calls["GetCategoryBySlug"], "GetCategoryBySlug")
	assert.True(t, calls["UpdateCategory"], "UpdateCategory")
	assert.True(t, calls["ListCategories"], "ListCategories")
	assert.True(t, calls["SoftDeleteCategory"], "SoftDeleteCategory")
	assert.True(t, calls["CountArticlesInCategory"], "CountArticlesInCategory")
	assert.True(t, calls["CreateArticle"], "CreateArticle")
	assert.True(t, calls["GetArticleByID"], "GetArticleByID")
	assert.True(t, calls["GetArticleBySlug"], "GetArticleBySlug")
	assert.True(t, calls["UpdateArticle"], "UpdateArticle")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["ListPublished"], "ListPublished")
	assert.True(t, calls["SoftDeleteArticle"], "SoftDeleteArticle")
	assert.True(t, calls["IncrementViews"], "IncrementViews")

	var z mocks.MockKnowledgebaseRepo
	{
		var ctx context.Context
		var c *domain.KBCategory
		z.CreateCategory(ctx, c)
	}
	{
		var ctx context.Context
		var id int64
		z.GetCategoryByID(ctx, id)
	}
	{
		var ctx context.Context
		var slug string
		z.GetCategoryBySlug(ctx, slug)
	}
	{
		var ctx context.Context
		var c *domain.KBCategory
		z.UpdateCategory(ctx, c)
	}
	{
		var ctx context.Context
		var includeHidden bool
		z.ListCategories(ctx, includeHidden)
	}
	{
		var ctx context.Context
		var id int64
		z.SoftDeleteCategory(ctx, id)
	}
	{
		var ctx context.Context
		var categoryID int64
		z.CountArticlesInCategory(ctx, categoryID)
	}
	{
		var ctx context.Context
		var a *domain.KBArticle
		z.CreateArticle(ctx, a)
	}
	{
		var ctx context.Context
		var id int64
		z.GetArticleByID(ctx, id)
	}
	{
		var ctx context.Context
		var slug string
		z.GetArticleBySlug(ctx, slug)
	}
	{
		var ctx context.Context
		var a *domain.KBArticle
		z.UpdateArticle(ctx, a)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		var categoryID int64
		var p ports.ListParams
		z.ListPublished(ctx, categoryID, p)
	}
	{
		var ctx context.Context
		var id int64
		z.SoftDeleteArticle(ctx, id)
	}
	{
		var ctx context.Context
		var id int64
		z.IncrementViews(ctx, id)
	}
}

func TestGenerated_MockNetworkStatusRepo(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockNetworkStatusRepo{
		CreateFn: func(ctx context.Context, n *domain.NetworkIssue) (r0 error) { calls["Create"] = true; return },
		GetByIDFn: func(ctx context.Context, id int64) (r0 *domain.NetworkIssue, r1 error) {
			calls["GetByID"] = true
			return
		},
		UpdateFn: func(ctx context.Context, n *domain.NetworkIssue) (r0 error) { calls["Update"] = true; return },
		ListFn: func(ctx context.Context, p ports.ListParams) (r0 []domain.NetworkIssue, r1 int64, r2 error) {
			calls["List"] = true
			return
		},
		ListActiveFn: func(ctx context.Context) (r0 []domain.NetworkIssue, r1 error) { calls["ListActive"] = true; return },
		SoftDeleteFn: func(ctx context.Context, id int64) (r0 error) { calls["SoftDelete"] = true; return },
	}

	{
		var ctx context.Context
		var n *domain.NetworkIssue
		m.Create(ctx, n)
	}
	{
		var ctx context.Context
		var id int64
		m.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var n *domain.NetworkIssue
		m.Update(ctx, n)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		m.List(ctx, p)
	}
	{
		var ctx context.Context
		m.ListActive(ctx)
	}
	{
		var ctx context.Context
		var id int64
		m.SoftDelete(ctx, id)
	}

	assert.True(t, calls["Create"], "Create")
	assert.True(t, calls["GetByID"], "GetByID")
	assert.True(t, calls["Update"], "Update")
	assert.True(t, calls["List"], "List")
	assert.True(t, calls["ListActive"], "ListActive")
	assert.True(t, calls["SoftDelete"], "SoftDelete")

	var z mocks.MockNetworkStatusRepo
	{
		var ctx context.Context
		var n *domain.NetworkIssue
		z.Create(ctx, n)
	}
	{
		var ctx context.Context
		var id int64
		z.GetByID(ctx, id)
	}
	{
		var ctx context.Context
		var n *domain.NetworkIssue
		z.Update(ctx, n)
	}
	{
		var ctx context.Context
		var p ports.ListParams
		z.List(ctx, p)
	}
	{
		var ctx context.Context
		z.ListActive(ctx)
	}
	{
		var ctx context.Context
		var id int64
		z.SoftDelete(ctx, id)
	}
}

func TestGenerated_MockGuestTicketCreator(t *testing.T) {
	calls := map[string]bool{}
	m := &mocks.MockGuestTicketCreator{
		CreateGuestTicketFn: func(ctx context.Context, in ports.GuestTicketInput) (r0 *domain.Ticket, r1 error) {
			calls["CreateGuestTicket"] = true
			return
		},
	}

	{
		var ctx context.Context
		var in ports.GuestTicketInput
		m.CreateGuestTicket(ctx, in)
	}

	assert.True(t, calls["CreateGuestTicket"], "CreateGuestTicket")

	var z mocks.MockGuestTicketCreator
	{
		var ctx context.Context
		var in ports.GuestTicketInput
		z.CreateGuestTicket(ctx, in)
	}
}
